### ISSUE TITLE
do we actually want to allow a `nameIndex` that's equal to `names`'s size?

### ISSUE THREAD

**Issue by dcrousso** [tc39/source-map-tests#25]
when dealing with `sourceIndex` and `sources`, we check for greater than _or equal to_ the size
> [...] if _sourceIndex_ is greater than or equal to _sources_’s [size](https://infra.spec.whatwg.org/#list-size), [...]

but when dealing with `nameIndex` and `names` we only check for greater than
> If _nameIndex_ is negative or greater than _names_’s [size](https://infra.spec.whatwg.org/#list-size), [...]

the `invalidMappingSegmentWithNameIndexOutOfBounds` test has `"names": ["foo"]` and `"mappings": "AAAAC"` which decodes decodes to `[0,0,0,0,1]` meaning that by the end `nameIndex` will be `1`, which is out of bounds for `names`

so i think either this test needs to be changed to at least `"mappings": "AAAAD"` or we need to adjust the spec to check for equal to with `nameIndex` and `names` as well

**Comment by takikawa** [comment]
Thanks for finding this, I suspect it's a bug in the spec and we should fix it there. WDYT @nicolo-ribaudo?
